on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build Docker Image
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t flaviiie/nginxtd:latest .
          docker images  # Afficher les images disponibles pour vérification

  push:
    name: Push Docker Image to Docker Hub
    runs-on: [self-hosted]
    needs: build  # Ce job ne s'exécute qu'après le job 'build'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push flaviiie/nginxtd:latest

